server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://15.206.79.238:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://15.206.79.238:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://15.206.79.238:1003
    cart:
      path: /cart/**
      url: http://15.206.79.238:1004/api/v1
